import { UserRole } from '../types';

export const RolePermissions = {
  DIRECTOR: {
    canViewDashboard: true,
    canViewPortfolio: true,
    canViewAudit: true,
    canViewUsers: true,
    canAddProject: true,
    canEditProject: true,
    canApproveVouchers: true,
    canApproveExpenses: true,
    canEditBudget: true,
    canUploadDocuments: true,
    canViewReports: true,
    canManageBilling: true,
  },
  MANAGER: {
    canViewDashboard: true,
    canViewPortfolio: true,
    canViewAudit: true,
    canViewUsers: false,
    canAddProject: true,
    canEditProject: true,
    canApproveVouchers: false,
    canApproveExpenses: false,
    canEditBudget: true,
    canUploadDocuments: true,
    canViewReports: true,
    canManageBilling: false,
  },
  FINANCE: {
    canViewDashboard: true,
    canViewPortfolio: true,
    canViewAudit: false,
    canViewUsers: false,
    canAddProject: false,
    canEditProject: false,
    canApproveVouchers: true,
    canApproveExpenses: false,
    canEditBudget: true,
    canUploadDocuments: true,
    canViewReports: true,
    canManageBilling: false,
  },
  AUDITOR: {
    canViewDashboard: true,
    canViewPortfolio: true,
    canViewAudit: true,
    canViewUsers: true,
    canAddProject: false,
    canEditProject: false,
    canApproveVouchers: false,
    canApproveExpenses: false,
    canEditBudget: false,
    canUploadDocuments: false,
    canViewReports: true,
    canManageBilling: false,
  },
  FINANCIADOR: {
    canViewDashboard: true,
    canViewPortfolio: true,
    canViewAudit: false,
    canViewUsers: false,
    canAddProject: false,
    canEditProject: false,
    canApproveVouchers: false,
    canApproveExpenses: false,
    canEditBudget: false,
    canUploadDocuments: false,
    canViewReports: true,
    canManageBilling: false,
  },
  RESPONSABLE_PROYECTO: {
    canViewDashboard: true,
    canViewPortfolio: true,
    canViewAudit: false,
    canViewUsers: false,
    canAddProject: false,
    canEditProject: true,
    canApproveVouchers: false,
    canApproveExpenses: false,
    canEditBudget: true,
    canUploadDocuments: true,
    canViewReports: true,
    canManageBilling: false,
  }
} as const;

export type Permission = keyof typeof RolePermissions['DIRECTOR'];

export const hasPermission = (role: UserRole, permission: Permission): boolean => {
  return RolePermissions[role]?.[permission] ?? false;
};
